Name: CPQ Config
ignoreDependencies: false
VlocityDataPackKeys:
    - CpqConfigurationSetup/AddPromoValidate
    - CpqConfigurationSetup/AllowOperationsOnDiscProducts
    - CpqConfigurationSetup/AllTriggers
    - CpqConfigurationSetup/AlwaysInsertMessageElement
    - CpqConfigurationSetup/AlwaysRegenerateV2AttributeFields
    - CpqConfigurationSetup/ApplyPromoToBundleWithExpiredChildItem
    - CpqConfigurationSetup/Attribute Check Mode
    - CpqConfigurationSetup/AttributeValueDisplaySortMode
    - CpqConfigurationSetup/AttrMatrixInfoCachePartition
    - CpqConfigurationSetup/B2BCmexBulkPricingIntegrationProcName
    - CpqConfigurationSetup/B2BCmexCreateSubOrderProcName
    - CpqConfigurationSetup/B2BCmexCreateSubOrderProcNameV2
    - CpqConfigurationSetup/B2BCmexEligibilityCalProcName
    - CpqConfigurationSetup/B2BCmexEligibilityMatrixName
    - CpqConfigurationSetup/B2BCmexEnterprisePPForOrderMemberOIs
    - CpqConfigurationSetup/B2BCmexEnterprisePPForQuoteMemberQLIs
    - CpqConfigurationSetup/B2BCmexQtyDiscountCalculationProcedure
    - CpqConfigurationSetup/B2BCmexSubmitOrdersProcName
    - CpqConfigurationSetup/B2BCmexSubmitSubOrderProcName
    - CpqConfigurationSetup/CacheAPI.BasketAPIPoolSize
    - CpqConfigurationSetup/CacheAPI.CacheManagement
    - CpqConfigurationSetup/CacheAPI.CombinationLimit
    - CpqConfigurationSetup/CacheAPI.CreateCartBatchSize
    - CpqConfigurationSetup/CacheAPI.CreateCartFromContextKey
    - CpqConfigurationSetup/CacheAPI.CustomGroupContextItems
    - CpqConfigurationSetup/CacheAPI.DeletePseudoRecords
    - CpqConfigurationSetup/CacheAPI.ExternalSystemAuthHeader
    - CpqConfigurationSetup/CacheAPI.ExternalSystemPartitionKey
    - CpqConfigurationSetup/CacheAPI.ExternalSystemURL
    - CpqConfigurationSetup/CacheAPI.GenericOffersAttribute
    - CpqConfigurationSetup/CacheAPI.GetOffersCacheRecLimit
    - CpqConfigurationSetup/CacheAPI.GetOffersVerCacheRecLimit
    - CpqConfigurationSetup/CacheAPI.GetRelOffersCacheRecComLimit
    - CpqConfigurationSetup/CacheAPI.GetRelOffersCacheRecLimit
    - CpqConfigurationSetup/CacheAPI.IncludeParentContextPLEs
    - CpqConfigurationSetup/CacheAPI.MaxCombinationLimit
    - CpqConfigurationSetup/CacheAPI.MaxGetOffersCacheRecLimit
    - CpqConfigurationSetup/CacheAPI.MaxGetRelOffersCacheRecLimit
    - CpqConfigurationSetup/CacheAPI.OptimizedBasketResponse
    - CpqConfigurationSetup/CacheAPI.PerfMode
    - CpqConfigurationSetup/CacheAPI.RegenerateBasket
    - CpqConfigurationSetup/CacheAPI.RegenerateBatchCacheProcessor
    - CpqConfigurationSetup/CacheAPI.RegenerateCatalogBatches
    - CpqConfigurationSetup/CacheAPI.RegenerateEntriesPartition
    - CpqConfigurationSetup/CacheAPI.RegenerateFutureDatedCache
    - CpqConfigurationSetup/CacheAPI.RemoveNonCacheableAttribInDCG
    - CpqConfigurationSetup/CacheAPI.SkinnyBasket
    - CpqConfigurationSetup/CacheAPI.SkinnyCtxDmsnCombinations
    - CpqConfigurationSetup/CacheAPI.TimeToLiveInDays
    - CpqConfigurationSetup/CacheAPI.TrimMode
    - CpqConfigurationSetup/CacheAPIFields
    - CpqConfigurationSetup/CacheAPIPartialConfigure
    - CpqConfigurationSetup/CacheAPIPartialConfigureProduct
    - CpqConfigurationSetup/CachedQueryMode
    - CpqConfigurationSetup/CacheEnabled
    - CpqConfigurationSetup/Cart Customizable Attribute Level
    - CpqConfigurationSetup/Cart Level Discount Approval Required
    - CpqConfigurationSetup/ConfigurationSnapshotLock
    - CpqConfigurationSetup/ContextRulesCacheMode
    - CpqConfigurationSetup/ContextRulesEnabled
    - CpqConfigurationSetup/ControlProduct2FieldsDuringCreation
    - CpqConfigurationSetup/CPQ Cart Preview Modal Use API
    - CpqConfigurationSetup/CPQ Toast Message Log Level
    - CpqConfigurationSetup/CpqCachePvtKey
    - CpqConfigurationSetup/CpqNextPricingPlan
    - CpqConfigurationSetup/CreateAdjForAbsZeroValue
    - CpqConfigurationSetup/CustomRuleMessageFieldName
    - CpqConfigurationSetup/DefaultAccountFieldset
    - CpqConfigurationSetup/DefaultEntityFilterEditFieldset
    - CpqConfigurationSetup/DefaultHierarchy
    - CpqConfigurationSetup/DefaultPowerUpdateJobThreshold
    - CpqConfigurationSetup/DefaultPricingPlan
    - CpqConfigurationSetup/DefaultSplitJobThreshold
    - CpqConfigurationSetup/DeleteServices
    - CpqConfigurationSetup/DeltaPrice
    - CpqConfigurationSetup/DeltaValidate
    - CpqConfigurationSetup/EnableMultiServiceBulkAction
    - CpqConfigurationSetup/EnableSupplementalOrderPricing
    - CpqConfigurationSetup/EnableUserNotifier
    - CpqConfigurationSetup/EnforceOfferMigrationOfferTypeMatch
    - CpqConfigurationSetup/ESMCreateSOForNonMemberProcNameV2
    - CpqConfigurationSetup/ESMCreateSubOrderForNonMemberProcName
    - CpqConfigurationSetup/ExcludedCatalogProductDefinitionJobs
    - CpqConfigurationSetup/ExpressBulkPricingIntegrationProcName
    - CpqConfigurationSetup/ExpressQtyDiscountCalculationProcedure
    - CpqConfigurationSetup/FDOStatuses
    - CpqConfigurationSetup/FilterRuleWithEligAvail
    - CpqConfigurationSetup/FindReferencesRowCountLimit
    - CpqConfigurationSetup/GuestHandlingEnabled
    - CpqConfigurationSetup/ImplicitPricing
    - CpqConfigurationSetup/ImplicitSaveMode
    - CpqConfigurationSetup/IncludeAddOnsAttributes
    - CpqConfigurationSetup/includeineligible
    - CpqConfigurationSetup/JsonInCore
    - CpqConfigurationSetup/LevelBasedApproach
    - CpqConfigurationSetup/LevelBasedPageSize
    - CpqConfigurationSetup/LevelBasedPagination
    - CpqConfigurationSetup/LockOrderAfterSubmitToOM
    - CpqConfigurationSetup/LogOdinNotifications
    - CpqConfigurationSetup/MarginCalculationType
    - CpqConfigurationSetup/MaxCPUTimePerTransaction
    - CpqConfigurationSetup/MaxHeapSizePerTransaction
    - CpqConfigurationSetup/MTSEnabled
    - CpqConfigurationSetup/Multiple Promotion Nodes Resolution
    - CpqConfigurationSetup/MultiServiceMasterOrderRecordTypes
    - CpqConfigurationSetup/MultiServiceMasterQuoteRecordTypes
    - CpqConfigurationSetup/MultiServiceSingleOrderRecordTypes
    - CpqConfigurationSetup/MultiServiceSingleQuoteRecordTypes
    - CpqConfigurationSetup/NeedContextForAttribConfig
    - CpqConfigurationSetup/NumberOfDMLPerTransaction
    - CpqConfigurationSetup/NumberOfQueriesPerTransaction
    - CpqConfigurationSetup/ObjectCopierPrice
    - CpqConfigurationSetup/ObjectCopierValidate
    - CpqConfigurationSetup/OrderItemIgnoredColumns
    - CpqConfigurationSetup/OriginalOrderCancellationStatusChanges
    - CpqConfigurationSetup/PaginationSize
    - CpqConfigurationSetup/PopulateAllActionVariants
    - CpqConfigurationSetup/PreventNegativeAdjustment
    - CpqConfigurationSetup/PriceBookRefreshBatchSize
    - CpqConfigurationSetup/PricingElementServiceLogging
    - CpqConfigurationSetup/PricingPlanHelperLogging
    - CpqConfigurationSetup/PricingPlanServiceLogging
    - CpqConfigurationSetup/Product Configuration Mode
    - CpqConfigurationSetup/ProductAttribJSONBatchJob
    - CpqConfigurationSetup/ProductAttribJSONBatchJob Update All
    - CpqConfigurationSetup/ProductAttributesBatchProcessorSize
    - CpqConfigurationSetup/ProductEligibilityDisplayAll
    - CpqConfigurationSetup/ProductEligibilityMatrixLogging
    - CpqConfigurationSetup/ProductHierarchyBatchProcessorSize
    - CpqConfigurationSetup/RemoveLineItemDCFields
    - CpqConfigurationSetup/RemoveNonCacheableAttribInDCG
    - CpqConfigurationSetup/RetainRecurringPriceDisconnectOrCancel
    - CpqConfigurationSetup/RollupActionCodeField
    - CpqConfigurationSetup/RunPCPInPostExecuteMethod
    - CpqConfigurationSetup/SaveProductAttribMetadataCache
    - CpqConfigurationSetup/SaveProductAttributeMetadata
    - CpqConfigurationSetup/ShouldConsiderDeletedItems
    - CpqConfigurationSetup/SimplePLERuleCacheMode
    - CpqConfigurationSetup/SingleFdoMode
    - CpqConfigurationSetup/Standard Pricing Plan
    - CpqConfigurationSetup/StrictSplitModeEnabled
    - CpqConfigurationSetup/Toggle Next Message Flag
    - CpqConfigurationSetup/UseAssetReferenceIdForParentAndRoot
    - CpqConfigurationSetup/UseWeights
    - CpqConfigurationSetup/UsingPromotions
    - CpqConfigurationSetup/UsingWeights
    - CpqConfigurationSetup/ValidateAndUpgradeV2Attributes
    - InterfaceImplementation/ABOAssetInterface
    - InterfaceImplementation/AccountContextInterface
    - InterfaceImplementation/ActivateFrameContractInterface
    - InterfaceImplementation/AddPricebookEntryInterface
    - InterfaceImplementation/AddProductInterface
    - InterfaceImplementation/ApprovalProcessInterface
    - InterfaceImplementation/ApprovalStatusInterface
    - InterfaceImplementation/AssetFilterInterface
    - InterfaceImplementation/AssetsContextInterface
    - InterfaceImplementation/AttributeGUIDBatchJobQuery
    - InterfaceImplementation/BillingProfileInterface
    - InterfaceImplementation/BulkXLIEditInterface
    - InterfaceImplementation/BundleContextInterface
    - InterfaceImplementation/CacheableFDO
    - InterfaceImplementation/CachedAPIResponse
    - InterfaceImplementation/CachedBasketPricerInterface
    - InterfaceImplementation/CachePopulation
    - InterfaceImplementation/CalculateUnitPriceInterface
    - InterfaceImplementation/CartContextInterface
    - InterfaceImplementation/CategoryGUIDBatchJobQuery
    - InterfaceImplementation/ChildItemSelectionInterface
    - InterfaceImplementation/CloneAdditionalObjects
    - InterfaceImplementation/CloneFieldListInterface
    - InterfaceImplementation/CMAttributeAssignmentInterface
    - InterfaceImplementation/CMCalculationMatrixRowInterface
    - InterfaceImplementation/CMCatalogInterface
    - InterfaceImplementation/CMCatalogProductRelationshipInterface
    - InterfaceImplementation/CMContextDimensionInterface
    - InterfaceImplementation/CMEntityFilterConditionInterface
    - InterfaceImplementation/CMEntityFilterInterface
    - InterfaceImplementation/CMPriceListEntryInterface
    - InterfaceImplementation/CMProduct2Interface
    - InterfaceImplementation/CMProductChildItemInterface
    - InterfaceImplementation/CMProductConfigurationProcedureInterface
    - InterfaceImplementation/CMProductRelationshipInterface
    - InterfaceImplementation/CMPromotionInterface
    - InterfaceImplementation/CMPromotionItemInterface
    - InterfaceImplementation/CMRuleAssignmentInterface
    - InterfaceImplementation/CMRuleInterface
    - InterfaceImplementation/CMVlocityAttachmentInterface
    - InterfaceImplementation/ContextDimensionMapperInterface
    - InterfaceImplementation/ContextEligibilityBatchJobRecord
    - InterfaceImplementation/ContextInputParserInterface
    - InterfaceImplementation/ContextRuleService
    - InterfaceImplementation/ContractContextInterface
    - InterfaceImplementation/ContractStateModelInterface
    - InterfaceImplementation/CpqAppHandler
    - InterfaceImplementation/CpqCalcMatrixRowSelectorInterface
    - InterfaceImplementation/CpqCalcMatrixVersionSelectorInterface
    - InterfaceImplementation/CPQCartCheckoutMessages
    - InterfaceImplementation/CpqPricingPlanStepSelectorInterface
    - InterfaceImplementation/CPQSubmitFlowInterface
    - InterfaceImplementation/CreateCart
    - InterfaceImplementation/CtxRulesPriceElementsOpenInterface
    - InterfaceImplementation/CtxRulesPriceListsOpenInterface
    - InterfaceImplementation/DataProfileBatchJobRecord
    - InterfaceImplementation/DCProductVersionBatchJobRecord
    - InterfaceImplementation/DCPromoVersionBatchJobRecord
    - InterfaceImplementation/DCTimeSliceListBatchJobRecord
    - InterfaceImplementation/DCTimeSlicesGeneratorBatchJobRecord
    - InterfaceImplementation/DCVersionInfoListBatchJobRecord
    - InterfaceImplementation/DeleteProductInterface
    - InterfaceImplementation/DiscountActivation
    - InterfaceImplementation/DiscountSelector
    - InterfaceImplementation/EligibilityContextInterface
    - InterfaceImplementation/FieldMapperInterface
    - InterfaceImplementation/FollowOnForAmend
    - InterfaceImplementation/FrameContractDiscountInterface
    - InterfaceImplementation/FreezeOrdAcceptedResponse
    - InterfaceImplementation/FreezeOrdRejectedResponse
    - InterfaceImplementation/GetConditionalTemplateItemsInterface
    - InterfaceImplementation/GetConditionalTemplateSectionsInterface
    - InterfaceImplementation/GetContractSignatureRequiredInterface
    - InterfaceImplementation/GetContractTemplateNameInterface
    - InterfaceImplementation/GetContractTermInterface
    - InterfaceImplementation/GetDocTemplateNameInterface
    - InterfaceImplementation/GetDocumentTemplateListInterface
    - InterfaceImplementation/GetFrameContractQueryWhereClauseInterface
    - InterfaceImplementation/GetItemsListInterface
    - InterfaceImplementation/GetOfferDetailsBatchJobRecord
    - InterfaceImplementation/GetOffersBatchJobRecord
    - InterfaceImplementation/GetOffersHierarchyBatchJobRecord
    - InterfaceImplementation/GetOffersItemBatchJobRecord
    - InterfaceImplementation/GetPricesBatchJobRecord
    - InterfaceImplementation/GetProductListInterface
    - InterfaceImplementation/GetRelatedOffersBatchJobRecord
    - InterfaceImplementation/GetUpdateContractListInterface
    - InterfaceImplementation/GroupContextInterface
    - InterfaceImplementation/GUIDGenerator
    - InterfaceImplementation/InsertMediaPrintIssues
    - InterfaceImplementation/IsContractDocumentEditableInterface
    - InterfaceImplementation/KeyUpdatableInterface
    - InterfaceImplementation/LandingPageSelectorInterface
    - InterfaceImplementation/LoadConfiguration
    - InterfaceImplementation/MakeParentProductInterface
    - InterfaceImplementation/MarginRangeLoader
    - InterfaceImplementation/MarginValidation
    - InterfaceImplementation/MSApplyToGroupInterface
    - InterfaceImplementation/MSMemberObjectSelector
    - InterfaceImplementation/MyInvoicesInterface
    - InterfaceImplementation/NewProductVersionInterface
    - InterfaceImplementation/ObjectCopierInterface
    - InterfaceImplementation/OdinAPIHandler
    - InterfaceImplementation/OdinAttributeFormatter
    - InterfaceImplementation/OdinClassifyResponse
    - InterfaceImplementation/OdinNotifFldFormatInterface
    - InterfaceImplementation/OdinNotificationClassifier
    - InterfaceImplementation/OdinOrderAccepted
    - InterfaceImplementation/OdinOrderActivated
    - InterfaceImplementation/OdinOrderInProgress
    - InterfaceImplementation/OdinOrderItemAccepted
    - InterfaceImplementation/OdinOrderItemActivated
    - InterfaceImplementation/OdinOrderItemAssetize
    - InterfaceImplementation/OdinOrderItemInProgress
    - InterfaceImplementation/OdinOrderItemRejected
    - InterfaceImplementation/OdinOrderQueued
    - InterfaceImplementation/OdinOrderRejected
    - InterfaceImplementation/OdinSubmitOrderExtraFields
    - InterfaceImplementation/OdinValidator
    - InterfaceImplementation/OpportunityContractFlagRollupInterface
    - InterfaceImplementation/OpptyScheduleInterface
    - InterfaceImplementation/OrderContractFlagRollupInterface
    - InterfaceImplementation/PostChangeHandlerInterface
    - InterfaceImplementation/PreConfigureHandlerInterface
    - InterfaceImplementation/PremisesInterface
    - InterfaceImplementation/PricebookDefaultInterface
    - InterfaceImplementation/PricingInterface
    - InterfaceImplementation/PricingManAdjEligibilityInterface
    - InterfaceImplementation/PricingSelectorInterface
    - InterfaceImplementation/ProcessBillingInterface
    - InterfaceImplementation/ProductAvailabilityInterface
    - InterfaceImplementation/ProductAvailabilityOpenInterface
    - InterfaceImplementation/ProductDefinitionInterface
    - InterfaceImplementation/ProductEligibilityInterface
    - InterfaceImplementation/ProductEligibilityOpenInterface
    - InterfaceImplementation/ProductSelectorInterface
    - InterfaceImplementation/ProductValidationInterface
    - InterfaceImplementation/PromotionWrapperBatchJobRecord
    - InterfaceImplementation/QueuedOrderSelector
    - InterfaceImplementation/QuoteContractFlagRollupInterface
    - InterfaceImplementation/RenewContractBatchJobProcessInterface
    - InterfaceImplementation/RenewContractBatchJobQueryInterface
    - InterfaceImplementation/RepricingInterface
    - InterfaceImplementation/RepricingLineItemSelectorInterface
    - InterfaceImplementation/RepricingManAdjEligibilityInterface
    - InterfaceImplementation/ResolveRefDate
    - InterfaceImplementation/RESTCPQInterface
    - InterfaceImplementation/RuleSetCombinationBatchJobRecord
    - InterfaceImplementation/RuleSetCombinationBatchJobRecord
    - InterfaceImplementation/SendFreezeToOM
    - InterfaceImplementation/SendSubmitToOM
    - InterfaceImplementation/SendUnfreezeToOM
    - InterfaceImplementation/SetUsageQuantity
    - InterfaceImplementation/SimplePromoSelector
    - InterfaceImplementation/SplitProductInterface
    - InterfaceImplementation/SubmitOrdAcceptedResponse
    - InterfaceImplementation/SubmitOrdProvAcceptedResponse
    - InterfaceImplementation/SubmitOrdRejectedResponse
    - InterfaceImplementation/SupplementalOrderService
    - InterfaceImplementation/SupplementForAmend
    - InterfaceImplementation/SupplementForCancel
    - InterfaceImplementation/SyncQuoteToOpptyInterface
    - InterfaceImplementation/SyncXLIs
    - InterfaceImplementation/TightestMatchInterface
    - InterfaceImplementation/TimePolicyInterface
    - InterfaceImplementation/TransactionContextInterface
    - InterfaceImplementation/UnfreezeOrdAcceptedResponse
    - InterfaceImplementation/UnfreezeOrdRejectedResponse
    - InterfaceImplementation/UnparentProductInterface
    - InterfaceImplementation/UpdateFrameContractInterface
    - InterfaceImplementation/UpdateProductInterface
    - InterfaceImplementation/UsageConfigLoader
    - InterfaceImplementation/UserContextInterface
    - InterfaceImplementation/UserNotifier
    - InterfaceImplementation/V3BasketXLI
    - InterfaceImplementation/V3CachedAPISelector
    - InterfaceImplementation/V3CachedResponse
    - InterfaceImplementation/V3CacheKeyGeneration
    - InterfaceImplementation/V3CachingService
    - InterfaceImplementation/V3CreateCartFromPool
    - InterfaceImplementation/V3PoolOrderSelector
    - InterfaceImplementation/V3PrepareResponse
    - InterfaceImplementation/V3PromotionService
    - InterfaceImplementation/V3PromotionWrapperService
    - InterfaceImplementation/V3QuerySelector
    - InterfaceImplementation/ValidateAddressInterface
    - InterfaceImplementation/ValidateModifyMediaPlan
    - InterfaceImplementation/XOMSupplementalOrderLifeCycle
VlocityTypesToFetch:
    - CpqConfigurationSetup
    - InterfaceImplementation
SalesforceTypesToFetch:
